# Ejercicios basicos con python

1. Implementar una función que tome un número entero positivo como parámetro y devuelva un
booleano indicando si el número ingresado es par.

In [ ]:
def par_impar(num):
    return num % 2 == 0

par_impar(3)

2. Implementar una función que tome un arreglo y devuelva la suma de todos sus elementos.

In [2]:
def suma_arreglo(arreglo):
    suma = 0
    for i in arreglo:
        suma += i
    return suma

suma_arreglo([1,2,3,4,5])

15

3. Implementar una función que tome un arreglo y un valor. La función debe devolver la cantidad de
veces que se repite el valor ingresado en el arreglo.

In [5]:
def contar_repeticiones(arreglo, numero):
    contador = 0
    for i in arreglo:
        if i == numero:
            contador += 1
    return contador

contar_repeticiones([1,2,3,4,5,2,5,5,5], 5)

4

4. Implementar una función que tome un arreglo y un valor. Debe devolver otro arreglo filtrando los elementos del array ingresado cuyos valores sean inferiores al valor ingresado por parámetro.

In [7]:
def filtrar_arreglo(arreglo, valor):
    nuevo_arreglo = []
    for i in arreglo:
        if i < valor:
            nuevo_arreglo.append(i)
    return nuevo_arreglo

filtrar_arreglo([1,2,3,4,5,6,7,8,9], 6)

[1, 2, 3, 4, 5]

6. Implementar una función que tome como parámetros dos arreglos de dos dimenciones (matrices) y
devuelva la suma de ambas matrices.

In [9]:
def sumar_matrices(matriz1, matriz2):
    matriz_suma = []
    for i in range(len(matriz1)):
        fila = []
        for j in range(len(matriz1[i])):
            fila.append(matriz1[i][j] + matriz2[i][j])
        matriz_suma.append(fila)
    return matriz_suma

sumar_matrices([[1,2,3],[4,5,6],[7,8,9]], [[9,8,7],[6,5,4],[3,2,1]])

[[10, 10, 10], [10, 10, 10], [10, 10, 10]]

7. Implementar una función que tome como parámetros dos arreglos de dos dimenciones (matrices) y devuelva la multiplicación de ambas matrices.

In [8]:
def multiplicar_matrices(matriz1, matriz2):
    matriz_producto = []
    for i in range(len(matriz1)):
        fila = []
        for j in range(len(matriz2[0])):
            suma = 0
            for k in range(len(matriz1[i])):
                suma += matriz1[i][k] * matriz2[k][j]
            fila.append(suma)
        matriz_producto.append(fila)
    return matriz_producto

multiplicar_matrices([[1,2,3],[4,5,6],[7,8,9]], [[9,8,7],[6,5,4],[3,2,1]])

[[30, 24, 18], [84, 69, 54], [138, 114, 90]]

## Ejercicios con Numpy
Leer la documentación de la librería (o páginas confiables de internet) y realizar los siguientes ejercicios.

In [2]:
import numpy as np

8. Crear un vector con valores dentro del rango 10 a 49

In [11]:
vector = np.arange(10, 50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

9. Crear una matriz 3x3 con valores de 0 a 8

In [12]:
matriz_3x3 = np.arange(9).reshape(3, 3)
matriz_3x3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. Crear una matriz identidad de 6x6

In [13]:
matriz_identidad_6x6 = np.eye(6)
matriz_identidad_6x6

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

12. Crear una matriz con valores al azar con forma 3x3x3

In [14]:
matriz_aleatoria_3x3x3 = np.random.random((3, 3, 3))
matriz_aleatoria_3x3x3

array([[[0.55734586, 0.04187099, 0.25302394],
        [0.04842418, 0.1390037 , 0.2900713 ],
        [0.00811657, 0.45745361, 0.25897871]],

       [[0.97460841, 0.77828141, 0.94941706],
        [0.69972975, 0.73243058, 0.5708848 ],
        [0.62902018, 0.82213776, 0.09939129]],

       [[0.00993801, 0.44718679, 0.07515382],
        [0.82994531, 0.22334379, 0.02082584],
        [0.67849439, 0.79738922, 0.06250767]]])

13. Encontrar los indices de los valores minimos y maximos de la anterior matriz

In [15]:
indice_min = np.unravel_index(np.argmin(matriz_aleatoria_3x3x3), matriz_aleatoria_3x3x3.shape)
indice_max = np.unravel_index(np.argmax(matriz_aleatoria_3x3x3), matriz_aleatoria_3x3x3.shape)

indice_min, indice_max

((0, 2, 0), (1, 0, 0))

14. Crear dos arreglos al azar A y B, vericar si son iguales coordenada a coordenada.

In [ ]:
size = 10
A = np.random.randint(5, size=size)
B = np.random.randint(5, size=size)

for n in range(size):
    print(f"Concidencia {n}: {A[n] == B[n]}")

15. Declarar 2 matrices y sumarlas utilizando la librería numpy.

In [20]:
size = (3,3)

m1 = np.random.randint(5, size=size)
m2 = np.random.randint(5, size=size)
(m1, m2)

(array([[1, 0, 1],
        [0, 1, 4],
        [0, 4, 4]]),
 array([[4, 1, 3],
        [4, 3, 3],
        [1, 0, 4]]))

In [21]:
mSuma = np.zeros(size)
for i in range(size[0]):
    for j in range(size[1]):
        mSuma[i][j] = m1[i][j] + m2[i][j]

mSuma

array([[5., 1., 4.],
       [4., 4., 7.],
       [1., 4., 8.]])

16. Declarar 2 matrices y multiplicarlas utilizando la librería numpy.

In [22]:
mProducto = np.zeros(size)

for i in range(size[0]):
    for j in range(size[1]):
        suma = 0
        for k in range(size[0]):
            suma += m1[i][k] * m2[k][j]
        mProducto[i][j] = suma

mProducto

array([[ 5.,  1.,  7.],
       [ 8.,  3., 19.],
       [20., 12., 28.]])